qc = [
    'Espcial QC.',
    'Só tem profissional.',
    'Nasceu pra jogar o jogo.',
    'HE tcholinhas.',
    '-27 liga.',
    'O que acontece no bomb fica no bomb.',
    'Essa smoke aí é pra ganhar espaço',
    'NA utility.',
    'Miscuzzi.',
    'Gênios Táticos.',
    'Mano, tem um newba tentando subir janela ha duas horas',
    'Mamei',
    'Vai mamar.',
    'Não para no tetris!',
    'Badaragens!',
    'Só :crocodile:',
    'No detalhe',
    'In the detail.',
    'NA',
    'Mato 35 y perco.',
    '30% de um spray é a fé que você deposita nele.',
    'O que acontece lá, fica lá.',
]
